### ISSUE TITLE
Add new brokers

### ISSUE THREAD

**Issue by tfukaza** [tfukaza/harvest#104]
Using documentation in `_base.py` and the example of `robinhood.py`, implement
- [ ] `TDAmeritrade`, using [robin_stock](https://github.com/jmfernandes/robin_stocks)
- [x] `WeBull`, using [webull](https://github.com/tedchou12/webull)
- [x] `Alpaca`, using [alpaca-trade-api-python](https://github.com/alpacahq/alpaca-trade-api-python)
- [x] `Kraken` using [python3-krakenex](https://github.com/veox/python3-krakenex)

This issue is marked as a `good first issue`, because it is supposed to be a litmus test of how easy it is to add a new broker support to Harvest, which is one of its selling point.

**Comment by shershah010** [comment]
Working on Alpaca

**Comment by shershah010** [comment]
For alpaca there are a lot of extra configurations that it supports so I was wondering if I should try to provide all of those or just stick to what has currently been defined. For example Alpaca supports `stop` and `limit stop` in addition to `limit`. Also Alpaca does not support options so there is that too.

**Comment by tfukaza** [comment]
I'd say stick with what is already defined. Adding too much functions can make compatibility with other brokers difficult.

**Comment by shershah010** [comment]
Working on Kraken, but will probably won't have too much time this week.

**Comment by shershah010** [comment]
Hey Tommy, kraken does not have normal asset codes they have these: https://support.kraken.com/hc/en-us/articles/360001185506-How-to-interpret-asset-codes

Also there is no typical buying and selling, there  are exchanging from one crypto to another or to various currencies. For example XXDGUSD is used to go from XXDG to USD and back. How should this be handled?

**Comment by tfukaza** [comment]
Asset codes can be converted. E.g. YahooBroker converts `BTC` to `BTCUSD`, which is the convention Yahoo Finance website uses for cryptocurrencies. Something similar can be done for Kraken. 

As for buying/selling, I think "converting" from US Dollars to, say, BTC is the same thing as buying BTC. I just checked by buying Bitcoins on Kraken myself, and the platform definitely supports buying crypto with US dollars in the traditional sense.

**Comment by shershah010** [comment]
Kraken supports other currencies such as Yen and Pounds. Should we prompt users to select what currency they want to use because that changes the prices I think.

**Comment by tfukaza** [comment]
For now I think we can hard-code USD but it might be interesting to support foreign currency in the future.

**Comment by tfukaza** [comment]
Closing this for now, since we need to focus on updating existing brokers.
