### ISSUE TITLE
[💡Feature Request] Expand Storage Support

### ISSUE THREAD

**Issue by shershah010** [tfukaza/harvest#105]
- [x] Support all DBs in SQLAlchemy
- [ ] Find a good way for people who want to use a DB to not have to install all packages for all databases, but only the database they want to use.
- [x] Write documentation on how to start using a database

**Comment by tfukaza** [comment]
One idea I had was to support SQLite, if it isn't supported by SQLAlchemy. IMO SQLite is actually the best for Harvest, since (at least for now) Harvest has no plans for a client-server model.

**Comment by tfukaza** [comment]
Also the second TODO goes hand-to-hand with #93, because we need to figure out a way to let users easily install dependencies that are not part of Harvest's core framework.

**Comment by shershah010** [comment]
SQLAlchemy supports sqllite. In fact the current version of the DBStorage only supports sqllite.
