### ISSUE TITLE
Add bdist

### ISSUE THREAD

**Issue by tfukaza** [tfukaza/harvest#108]
Create bdist for Mac, Windows, and UNIX to speed up installation.

**Comment by shershah010** [comment]
Would it be better to just create a `whl` and have users install it via `pip install harvest-0.1.0-py3-none-any.whl` or `pip install harvest-0.1.0-py3-none-any.whl[Robinhood]`

**Comment by tfukaza** [comment]
If I understand it right, bdist and wheel are somewhat synonymous. So yes, you can just create a whl. I'm thinking after v0.2 is released, or possibly sometime earlier, I will upload harvest to PyPI.
