### ISSUE TITLE
[📝Documentation] Style Guide and Logging Questions

### ISSUE THREAD

**Issue by shershah010** [tfukaza/harvest#173]
**What needs more documentation?**
Specific style-guide questions.

**Is there any information you want in particular?**
I think Harvest is at the point where we should add linting to make the code more uniform. What are your thoughts?

Should we uses double quotes or single quotes because I think I alternated a few times?

When should debug, warning, critical, and error be logged and when should we raise Exceptions? I like raising exceptions because I don't want to have users code continue running after an error out of fear it might hurt their algo.

**Comment by tfukaza** [comment]
- I don't have a specific linter in mind, but linting is a good idea for sure. Maybe Black?
- I've been changing my mind about the Exception/warning thing for a while, but as of now I think you're right, we should treat errors as Exceptions.
