### ISSUE TITLE
Better testing framework

### ISSUE THREAD

**Issue by tfukaza** [tfukaza/harvest#3]
The current testing framework is very minimal. Ideally, the following things should be tested:

- [x] Every endpoint for brokers
- [x] Trader/TestTrader classes

**Comment by shershah010** [comment]
Do you want to use something like Github CI or Circle CI or even Jenkins for CI/CD or just adding more tests.

**Comment by tfukaza** [comment]
I think given the current scale of the project GitHub CI will be enough.
