### ISSUE TITLE
Decouple the Trader class from the Broker and Algo classes as much as possible

### ISSUE THREAD

**Issue by shershah010** [tfukaza/harvest#30]
Right now certain functions in the Broker and Algo class require the trader class to be initialized. This makes it hard to test these classes independently. It also will make it hard to explain each class since there is a large degree of dependence. Refactor the Broker classes and the Algo classes to be able to preform without needed a Trader class. The only exception should be when the trader class is defined and connected with the Broker and Algo class, can those classes use the Trader.

**Comment by tfukaza** [comment]
This seems like a pretty big rewrite, so I'll merge all the branches to main right now before PRs get really complicated later.
