### ISSUE TITLE
Rebase code

### ISSUE THREAD

**Issue by tfukaza** [tfukaza/harvest#58]
The `Trader` and `TestTrader` has a very confusing way of fetching and saving data. The code should be rebased to address this.

**Comment by shershah010** [comment]
I think I am currently working on this by refactoring the storing of stock data to brokers. So I can work on this issue.

**Comment by tfukaza** [comment]
#42 right? That one was more focused on the `Trader` and `Broker`, this issue is focused more on `TestTrader` so I think we can work separately for now. Though I admit the merge conflict will probably be messier than usual 😅
