### ISSUE TITLE
[💡Feature Request] Api for Webull and TD, Moomoo

### ISSUE THREAD

**Issue by pradeephyd** [tfukaza/harvest#69]
**Describe the feature**

**Comment by tfukaza** [comment]
WeBull and TD is definitely on our TODO👍. WeBull is already mentioned in #17, and TD is planned down the road. MooMoo might be up for debate, as it is not as widely used (at least as far as I know) compared to WeBull and TD.

**Comment by tfukaza** [comment]
Making this an issue for v0.2
