### ISSUE TITLE
[🪰BUG]pip install failed

### ISSUE THREAD

**Issue by pradeephyd** [tfukaza/harvest#71]
Tried to install harvest using pip command

pip install -e git+https://github.com/tfukaza/harvest.git
ERROR: Could not detect requirement name for 'git+https://github.com/tfukaza/harvest.git', please specify one with #egg=your_package_name
WARNING: You are using pip version 20.2.3; however, version 21.1.3 is available.
You should consider upgrading via the 'c:\python39\python.exe -m pip install --upgrade pip' command.

**Comment by tfukaza** [comment]
There was a mistake in the documentation, it has been fixed now.
