### ISSUE TITLE
[💡Feature Request]Monitor options price

### ISSUE THREAD

**Issue by pradeephyd** [tfukaza/harvest#72]
**Describe the feature**
it is good to monitor options price for a particular strike price, so based on that we can sell or trigger stop/take profit.

**Comment by tfukaza** [comment]
This can be done by using `get_option_market_data` and `get_chain_data`. See this example: https://github.com/tfukaza/harvest/blob/8234a8bcfa7f70ac5f3eb3a337b0d2bd1da34aae/examples/options.py#L22-L39

**Comment by pradeephyd** [comment]
In dummy broker orders, can we query last sale and confirm order. Just an idea to be more accurate 😜

**Comment by tfukaza** [comment]
That's an interesting idea... I'll add it to the TODO.

**Comment by tfukaza** [comment]
This issue is now part of #95
