### ISSUE TITLE
[🪰BUG]Authentication issue

### ISSUE THREAD

**Issue by pradeephyd** [tfukaza/harvest#79]
I`m i missing something the OTP is of 4 digits but RH requires 6 digits.

![Capture2](https://user-images.githubusercontent.com/16257956/125506178-34d2c783-3b84-427b-8916-5f7cb38e4ea4.PNG)

**Comment by tfukaza** [comment]
Are you using Python2 by any chance? Harvest is only supported on Python3.8+

**Comment by tfukaza** [comment]
I can't reproduce this issue, it seems to be an issue with the terminal and not Harvest. VSCode terminal does tend to be a bit buggy sometimes, so in the meantime you can try using another terminal.
