### ISSUE TITLE
[🪰BUG]Yahoo earnings not working

### ISSUE THREAD

**Issue by pradeephyd** [tfukaza/harvest#84]
Yahoo earnings not working and missing package dependency in setup.py.
please add get earnings between dates.

install_requires=[
        'pandas',
        'finta',
        'pyyaml',
        'tqdm',
        'pytz'
    ],

**Comment by tfukaza** [comment]
@pradeephyd Can you elaborate on "add get earnings between dates"? I'm assuming you mean you want a feature to fetch earning dates for a specific company.

**Comment by pradeephyd** [comment]
> @pradeephyd Can you elaborate on "add get earnings between dates"? I'm assuming you mean you want a feature to fetch earning dates for a specific company.

get all companies earnings on particular date or between dates

**Comment by tfukaza** [comment]
Interestingly this feature actually exists, although it has been disabled temporarily since the interface was a little messy. I might bring it back in v0.2.

**Comment by pradeephyd** [comment]
> Interestingly this feature actually exists, although it has been disabled temporarily since the interface was a little messy. I might bring it back in v0.2. It's in `plugins/yahoo.py` if you're interested.

That's great and really appreciate, if you make it work :)
