### ISSUE TITLE
[💡Feature Request] Get historical options price

### ISSUE THREAD

**Issue by pradeephyd** [tfukaza/harvest#89]
using this link https://www.dolthub.com/repositories/post-no-preference/options we can get historical options prices from more than 2 years. seems the database can be accessed using https://github.com/dolthub/doltpy 

It's a game-changer nobody implements yet with more than 2 years of historical options price. harvest will be the first.

**Comment by tfukaza** [comment]
I'm mixed on this one, since it is a great feature to add, but at the same time it looks like the database is compiled by a third-party enthusiast meaning it is not a reliable source. That being said, this might be a great candidate for a plugin - #93

**Comment by pradeephyd** [comment]
Sounds Good 👍
