### ISSUE TITLE
`ticker` or `symbol` for the short name for company names

### ISSUE THREAD

**Issue by shershah010** [tfukaza/harvest#9]
Sometimes we use `ticker` and other times we use `symbol` variable names to refer to short names for companies (ie AAPL for Apple).

Pick one and ensure that we only use that.

**Comment by tfukaza** [comment]
It should be `symbol`. I originally used `ticker` but I recently learned `ticker` technically refers to the price data itself, not the symbol (like AAPL). Most variables should now use `symbol` but I might have forgotten to convert some.
